program:
  root_path: C:\Users\a760408\CODE\TheLife\
  logs:
    level: info  # debug, info, warning, error
  drawings:
    dpi: 200
    height: 10  # In inches
    width: 10  # In inches

world:
  # The world is a squared grid with a radius length of `size`
  # The Distance Unit (DU) is 1
  # All sqared units (1x1) of the world contains one of many components
  # The simulation runs for `simulation_duration` days
  # `population_limit` individuals will be added
  size: 8
  simulation_duration: 15
  population_limit: 20

cells:
  dna_size: 0.001  # In Mbp (milions base pairs)
  evolution:
    mutation_rate: 0.1  # 0.1% of mutation chance
  energy:
    maximum: 100
  reproduction:
    energy_cost: 10
