program:
  root_path: C:\Users\a760408\CODE\TheLife\
  logs:
    level: info  # debug, info, warning, error
  drawings:
    dpi: 200
    height: 10  # In inches
    width: 10  # In inches

world:
  size: 15
  life:
    days: 15  # Number of days to live
  population:
    limit: 1

cells:
  dna_size: 0.001  # In Mbp (milions base pairs)
  evolution:
    mutation_rate: 0.1  # 0.1% of mutation chance
  energy:
    maximum: 100
  reproduction:
    energy_cost: 10
